-- ═══════════════════════════════════════════════════════════════
-- 3D Agora Lab — MASTER SEED (all products + manufacturing costs)
-- Run as ONE block in Supabase SQL Editor
-- To re-run: prefix with DELETE FROM public.products; ALTER SEQUENCE products_id_seq RESTART WITH 1;
-- ═══════════════════════════════════════════════════════════════

-- ── Core 37 products (explicit IDs 1-37) ──
INSERT INTO public.products (id,name,slug,category_id,sale_title,description,design_source,price_cop,images,video_url,tags) VALUES
(1,'Lámpara de mesa diseño musgo','lampara-musgo',1,'Lámpara de mesa - ambiente','Lámpara diseño musgo orgánica. Su forma natural e iluminación suave la convierten en una pieza decorativa perfecta.','Mossglow Organic Table Lamp – MakerWorld',35000,ARRAY['/store/assets/products/mossglow-lamp-1.jpg','/store/assets/products/mossglow-lamp-2.jpg','/store/assets/products/mossglow-lamp-3.jpg','/store/assets/products/mossglow-lamp-4.jpg','/store/assets/products/mossglow-lamp-5.jpg','/store/assets/products/mossglow-lamp-duo.jpg','/store/assets/products/mossglow-market.png'],'/store/assets/videos/mossglow-lamp-video.mp4',ARRAY['lámpara','musgo','decoración','hogar']),
(2,'Lámpara de mesa elegante acanalada','lampara-acanalada',1,'Lámpara de mesa - ambiente','Perfecta para la sala de estar, el dormitorio o la oficina.','Onda – MakerWorld',35000,ARRAY['/store/assets/products/lamps-colors.jpg','/store/assets/products/lamps-designs-colors.jpg'],NULL,ARRAY['lámpara','onda','elegante']),
(3,'Soporte cepillos de cabello','soporte-cepillos',2,'Soporte organizador cepillos','Capacidad para 8 cepillos. Ideal para organizar.','Soporte para cepillos – MakerWorld',15000,ARRAY['/store/assets/products/cathedral-organizer-makeup.jpg'],'/store/assets/videos/cathedral-organizer-vid.mp4',ARRAY['soporte','cepillos','belleza']),
(4,'Porta vasos monstera','porta-vasos-monstera',1,'Porta vasos monstera','Juego de Posavasos de Hoja de Monstera con soporte.','Monstera – MakerWorld',25000,ARRAY['/store/assets/products/IMG_4275.jpg','/store/assets/products/IMG_4276.jpg'],'/store/assets/videos/IMG_4277.mp4',ARRAY['posavasos','monstera']),
(5,'Organizador mostrador de llaveros','organizador-llaveros',1,'Mostrador organizador de llaveros','Organizador giratorio tipo árbol con múltiples ganchos para exhibir llaveros y accesorios. Estilo minimalista.','Organizador – MakerWorld',20000,ARRAY['/store/assets/products/keychain-organizer.jpg','/store/assets/products/keychain-organizer-1lvl.jpg','/store/assets/products/keychain-organizer-empty.jpg'],'/store/assets/videos/keychain-organizer-video.mp4',ARRAY['organizador','llaveros','mostrador','exhibidor']),
(6,'Organizador de maquillaje gótico','organizador-maquillaje-gotico',2,'Organizador de maquillaje','Acabado en negro mate con toque gótico sofisticado.','Organizador Gótico – MakerWorld',30000,ARRAY['/store/assets/products/cathedral-organizer-makeup.jpg'],'/store/assets/videos/cathedral-jewelry-organizer-video.mp4',ARRAY['organizador','maquillaje','gótico']),
(7,'Lámpara de Mesa Orgánica Velo Lunelle','lampara-lunelle',1,'Lámpara de mesa - ambiente','Pantalla suave y translúcida con base escultural texturizada.','Lunelle – MakerWorld',45000,ARRAY['/store/assets/products/lunelle-lamp-design.webp','/store/assets/products/lunelle-lamp-photo.jpg','/store/assets/products/lunelle-lamp-photo-2.jpg','/store/assets/products/lunelle-lamp-vid-2-thumb.jpg'],'/store/assets/videos/lunelle-lamp-video.mp4',ARRAY['lámpara','lunelle','velo']),
(8,'Lámpara de mesa ambiental Solenne','lampara-solenne',1,'Lámpara de mesa - ambiente','Forma orgánica refinada con cálido brillo ambiental.','Solenne – MakerWorld',45000,ARRAY['/store/assets/products/solenne-lamp-design.webp'],NULL,ARRAY['lámpara','solenne','ambiental']),
(9,'Lámpara de mesa Elarion','lampara-elarion',1,'Lámpara de mesa - ambiente','Inspirada en hojas superpuestas y texturas botánicas.','Elarion – MakerWorld',45000,ARRAY['/store/assets/products/elarion-lamp-design.webp'],NULL,ARRAY['lámpara','elarion','botánica']),
(10,'Lámpara de mesa olas minimalista','lampara-olas',1,'Lámpara de mesa - ambiente','Diseño minimalista con forma de ola.','La Ola – MakerWorld',35000,ARRAY['/store/assets/products/lamps-colors.jpg'],NULL,ARRAY['lámpara','olas']),
(11,'Lámpara ondulada minimalista','lampara-ondulada',1,'Lámpara de mesa - ambiente','Diseño moderno y minimalista.','Waved Lamp – MakerWorld',35000,ARRAY['/store/assets/products/lamps-designs-colors.jpg'],NULL,ARRAY['lámpara','ondulada']),
(12,'Lámpara acanalada reloj de arena','lampara-reloj-arena',1,'Lámpara de mesa - ambiente','Conicidad interna de reloj de arena con hermosos gradientes de luz.','Reloj de arena – MakerWorld',40000,ARRAY['/store/assets/products/lamps-colors.jpg'],NULL,ARRAY['lámpara','reloj de arena']),
(13,'Abrelatas lazo estampado vaca','abrelatas-lazo-vaca',2,'Abrelatas','Abrelatas con lazo estampado de vaca.','Abrelatas lazo – MakerWorld',5000,ARRAY['/store/assets/products/cow-canopener.jpg'],NULL,ARRAY['abrelatas','vaca']),
(14,'Abrelatas vaca','abrelatas-vaca',2,'Abrelatas','Abridor de lengüetas con diseño de vaca.','Abridor vaca – MakerWorld',5000,ARRAY['/store/assets/products/cow-canopener.jpg'],NULL,ARRAY['abrelatas','vaca']),
(15,'Abrelatas concha de mar','abrelatas-concha',2,'Abrelatas, protector de uñas','Diseño de concha marina.','Concha – MakerWorld',5000,ARRAY['/store/assets/products/shell-canopener.jpg','/store/assets/products/sheel-canopener.jpg'],NULL,ARRAY['abrelatas','concha']),
(16,'Clicker charm dumpling','clicker-dumpling',3,'Clicker','Mini dumpling fidget toy.','Dumpling – MakerWorld',8000,ARRAY['/store/assets/products/milo-clicker-1.jpg','/store/assets/products/milo-clicker-2.jpg'],'/store/assets/videos/milo-clicker-video.mp4',ARRAY['clicker','dumpling']),
(17,'Clicker charm Sanrio','clicker-sanrio',3,'Clicker','Kuromi, Keroppi, Cinnamoroll, Melody.','Sanrio – MakerWorld',8000,ARRAY['/store/assets/products/duquesa-clicker.jpg','/store/assets/products/duquesa-clicker-2.jpg'],'/store/assets/videos/duquesa-clicker-vid.mp4',ARRAY['clicker','sanrio']),
(18,'Clicker charm corazón puffy','clicker-corazon',3,'Clicker','Corazón hinchado.',NULL,8000,ARRAY['/store/assets/products/pug-clicker.jpg','/store/assets/products/pug-clicker2.jpg'],'/store/assets/videos/pug-clicker-vid.mp4',ARRAY['clicker','corazón']),
(19,'Clicker charm breakfast','clicker-breakfast',3,'Clicker','Paquete Desayuno Americano.',NULL,8000,ARRAY['/store/assets/products/milo-clicker-1.jpg'],'/store/assets/videos/milo-clicker-video.mp4',ARRAY['clicker','breakfast']),
(20,'Abrelatas Golden Retriever','abrelatas-golden',3,'Abrelatas, protector de uñas','Golden Retriever.',NULL,5000,ARRAY['/store/assets/products/retriever-canopener.jpg','/store/assets/products/retriever-keychain.jpg','/store/assets/products/retriever-keychain-2.jpg','/store/assets/products/retriever-keychain-green.jpg'],'/store/assets/videos/retriever-keychain-video.mp4',ARRAY['abrelatas','retriever']),
(21,'Abrelatas gatos variados','abrelatas-gatos',3,'Abrelatas, protector de uñas','Gatito lindo.',NULL,5000,ARRAY['/store/assets/products/cat-canopener.jpg','/store/assets/products/cat-keychain.jpg'],'/store/assets/videos/cat-keychain-video.mp4',ARRAY['abrelatas','gatos']),
(22,'Abrelatas clicker French Mani','abrelatas-french',3,'Abrelatas, protector de uñas','French Mani combo.',NULL,7000,ARRAY['/store/assets/products/frida-canopener.jpg'],NULL,ARRAY['abrelatas','french mani']),
(23,'Abrelatas kawaii','abrelatas-kawaii',3,'Abrelatas, protector de uñas','Llaveros abrelatas Kawaii.',NULL,5000,ARRAY['/store/assets/products/cute-ghost-keychain.jpg'],'/store/assets/videos/cute-ghost-canopener.mp4',ARRAY['abrelatas','kawaii']),
(24,'Abrelatas Hello Kitty','abrelatas-hellokitty',3,'Abrelatas, protector de uñas','Cinnamoroll / Sanrio.',NULL,5000,ARRAY['/store/assets/products/hellokitty-keychain.jpg'],NULL,ARRAY['abrelatas','hello kitty']),
(25,'Lámpara de mesa orgánica Calyra','lampara-calyra',1,'Lámpara de mesa - ambiente','Lámpara decorativa orgánica de escritorio.','Calyra – MakerWorld',40000,ARRAY['/store/assets/products/lamps-designs-colors.jpg'],NULL,ARRAY['lámpara','calyra']),
(26,'Soporte sujetador control Wii','soporte-wii',3,'Control','Soporte Wii Remote.',NULL,12000,ARRAY['/store/assets/products/wii-control.jpg','/store/assets/products/wii-controls.jpg','/store/assets/products/wii-controls-2.jpg'],NULL,ARRAY['soporte','wii']),
(27,'Soporte control Wii Mario','soporte-wii-mario',3,'Control','Tubería Warp de Mario.',NULL,15000,ARRAY['/store/assets/products/wii-control-organizer.jpg','/store/assets/products/wii-control-organizer-2.jpg'],NULL,ARRAY['soporte','wii','mario']),
(28,'Soporte organizador Wii','soporte-wii-org',3,'Control','Organizador Nintendo Wii.',NULL,15000,ARRAY['/store/assets/products/wii-control-organizer-3.jpg','/store/assets/products/wii-control-organizer-4.jpg','/store/assets/products/wii-control-organizer-front.jpg'],NULL,ARRAY['soporte','wii']),
(29,'Organizador de gorras','organizador-gorras',4,'Organizador','Soporte de sombreros montaje en pared.',NULL,15000,ARRAY['/store/assets/products/keychain-organizer.jpg'],'/store/assets/videos/keychain-organizer-video.mp4',ARRAY['organizador','gorras']),
(30,'Cofre Zelda Switch','cofre-zelda',3,'Gaming','Cofre Bokoblin soporte Switch.',NULL,25000,ARRAY['/store/assets/products/gold-dragon.jpg'],'/store/assets/videos/gold-dragon-vid.mp4',ARRAY['zelda','switch']),
(31,'Estuche viaje joyas sardinas','estuche-sardinas',3,'Accesorios','Estuche joyas lata de sardinas.',NULL,18000,ARRAY['/store/assets/products/shell-keychain.jpg'],NULL,ARRAY['estuche','joyas']),
(32,'Espada Maestra Ancestral','espada-maestra',3,'Gaming','Santuario Princesa Silente.',NULL,35000,ARRAY['/store/assets/products/gold-dragon.jpg'],NULL,ARRAY['espada','zelda']),
(33,'Imanes nevera cabeza de perro','imanes-perro',3,'Imanes','Set 12 imanes perro.',NULL,15000,ARRAY['/store/assets/products/bulldog-keychain.jpg'],'/store/assets/videos/bulldog-keychain-video.mp4',ARRAY['imanes','perro']),
(34,'Abrelatas Schnauzer','abrelatas-schnauzer',3,'Abrelatas, protector de uñas','Diseño Schnauzer.',NULL,5000,ARRAY['/store/assets/products/frida-canopener.jpg'],NULL,ARRAY['abrelatas','schnauzer']),
(35,'Llavero perro Maltés','llavero-maltes',3,'Llavero','Maltés lindo.',NULL,5000,ARRAY['/store/assets/products/benzai-keychain.jpg'],'/store/assets/videos/benzai-keychain-video.mp4',ARRAY['llavero','maltés']),
(36,'Llaveros razas de perros','llaveros-perros',3,'Llavero','Pocket Pups.',NULL,5000,ARRAY['/store/assets/products/all-keychain-designs.jpg'],'/store/assets/videos/all-keychain-design-vid.mp4',ARRAY['llavero','perros']),
(37,'Llavero Shih Tzu','llavero-shihtzu',3,'Llavero','4 Colores 60mm.',NULL,5000,ARRAY['/store/assets/products/kiss-keychain.jpg'],'/store/assets/videos/kiss-keychain-video.mp4',ARRAY['llavero','shih tzu']);

-- ── Fix sequence before auto-ID inserts ──
SELECT setval('products_id_seq', (SELECT MAX(id) FROM public.products));

-- ── Extra products (auto-generated IDs 38+) ──
INSERT INTO public.products (name,slug,category_id,sale_title,description,price_cop,images,video_url,tags) VALUES
('Lámpara Stitch personalizada','lampara-stitch',1,'Lámpara personalizada Stitch','Lámpara con diseño de Stitch. Impresión 3D.',65000,ARRAY['/store/assets/products/stitch-lamp.jpg','/store/assets/products/stitch-lamp-personalizado.jpg','/store/assets/products/stitch-personalizado-front.jpg','/store/assets/products/stitch-personalizado-encendido.jpg','/store/assets/products/stitch-personalizado-luz.jpg'],'/store/assets/videos/stitch-lamp-encendido.mp4',ARRAY['lámpara','stitch','personalizada']),
('Llavero Golden Retriever','llavero-retriever',3,'Llavero','Golden Retriever en colores.',5000,ARRAY['/store/assets/products/retriever-keychain.jpg','/store/assets/products/retriever-keychain-2.jpg','/store/assets/products/retriever-keychain-green.jpg'],'/store/assets/videos/retriever-keychain-video.mp4',ARRAY['llavero','retriever']),
('Llavero gato Salem','llavero-salem',3,'Llavero','Gato Salem.',5000,ARRAY['/store/assets/products/salem-keychain.jpg','/store/assets/products/salem-keychain-2.jpg'],'/store/assets/videos/salem-design-video.mp4',ARRAY['llavero','gato','salem']),
('Llavero alas de ángel','llavero-alas',3,'Llavero','Alas de ángel.',5000,ARRAY['/store/assets/products/wings-keychain.jpg'],'/store/assets/videos/wings-keychain-vid.mp4',ARRAY['llavero','alas']),
('Llavero ganso','llavero-ganso',3,'Llavero','Ganso divertido.',5000,ARRAY['/store/assets/products/goose-keychain.jpg'],NULL,ARRAY['llavero','ganso']),
('Llavero lazo','llavero-lazo',3,'Llavero','Lazo elegante.',5000,ARRAY['/store/assets/products/bow-keychain.jpg'],'/store/assets/videos/bow-keychain-video.mp4',ARRAY['llavero','lazo']),
('Llavero Frida','llavero-frida',3,'Llavero','Frida Kahlo.',5000,ARRAY['/store/assets/products/frida-keychain.jpg'],NULL,ARRAY['llavero','frida']),
('Llavero Firmes Patria','llavero-firmes',3,'Llavero','Patriótico Firmes.',5000,ARRAY['/store/assets/products/firmes-patria-keychain.jpg','/store/assets/products/firmes-plata-keychain.jpg'],NULL,ARRAY['llavero','patria']),
('Dragón chino dorado','dragon-dorado',3,'Decoración','Figura dragón dorado 3D.',35000,ARRAY['/store/assets/products/gold-dragon.jpg'],'/store/assets/videos/gold-dragon-vid.mp4',ARRAY['dragón','dorado']),
('Llavero gato','llavero-gato',3,'Llavero','Gatito lindo.',5000,ARRAY['/store/assets/products/cat-keychain.jpg'],'/store/assets/videos/cat-keychain-video.mp4',ARRAY['llavero','gato']),
('Llavero bulldog','llavero-bulldog',3,'Llavero','Bulldog lindo.',5000,ARRAY['/store/assets/products/bulldog-keychain.jpg'],'/store/assets/videos/bulldog-keychain-video.mp4',ARRAY['llavero','bulldog']);

-- ── Manufacturing costs ──
INSERT INTO public.manufacturing_costs (product_id,date,print_hours,filament_grams,filament_id,kwh_used,machine_hours,extras_cost,extras_desc,total_cost,sell_price,margin_pct) VALUES
(1,'2026-08-01',0.1,150,7,3.15,21,0,NULL,27008,35000,29.6),
(20,'2026-08-08',0,10,6,0.05,0.5,600,'(10:2)',1302,5000,284.1),
(18,'2026-08-20',0.1,100,6,1,6,7000,'(4:7)',24322,25000,2.8);

